---
abstract: 'Non-regional L<SMS::Send> driver for the L<http://wadja.com>'
author:
  - 'Dan Dascalescu <dandv@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMS-Send-Wadja
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  SMS::Send::Driver: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0
